name: Style Check

on: [pull_request, push]

jobs:
  check-formatting:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - uses: per1234/artistic-style-action@v1
      with:
          options-file-path: 'astyle.ini'
          name-patterns: |
            - '*.cpp'
            - '*.h'
